### ISSUE TITLE
provide a full workflow to explain how to work with a file from beginning to end

### ISSUE THREAD

**Issue by LinguList** [LoanpyDataHub/loanpy#15]
This would help to run through loanpy.

**Comment by LinguList** [comment]
could be a jupyter notebook (I don't like them, but people do)

**Comment by martino-vic** [comment]
Yes, was planning to do this. Jupyter doesn't work on my computer, am just trying to set up a notebook on google colab instead but it's unexpectedly buggy.

**Comment by martino-vic** [comment]
Sorry I think I misunderstood this at first, I thought of providing a notebook with the snippets from the documentation, but this turned out more difficult than expected, so skipping that after all.

As to the full workflow: I was thinking to provide that in form of a blog post, since the "step 1, step2, step3" structure would come in handy. I don't think a jupyter-notebook would be feasible for that anymore (for version one it would have been). It works through CLDF-commands now and consists of 3 steps:

1. extracting sound changes & optimising parameters from the etymological data with sanity.py and qfysc.py (ronatasbertawot)
2. applying the extracted data to predict loanword adaptation (streitberggothic) and backwards reconstructing (gerstnerhungarian) with adrc.py
3. creating a new repository with the matches found (martinovicgothun) with loanfinder.py

Each of these steps would modify the cldf repository, e.g. step1 adds soundchanges.csv, step2 would add a column with predicted loanword adaptations to forms.csv etc.

**Comment by LinguList** [comment]
Okay, so this sounds like three blog post, a series. You will have to explain quite some parts, and I see myself being interested in discussing terminology and methods and checking if you have covered all literature, or if I can learn a bit more. You should think already about the titles for the three blog posts. The first is clearly what I call "sound law induction".  See my talk handout [here](http://lingulist.de/documents/papers/list-2019-ichl-keynote-handout.pdf).

**Comment by LinguList** [comment]
The second part "Predicting Loanword Adaptation", nice. The third part would then be the qualitative part, right? Or "computer-assisted". You check if those make sense or not. Here, I'd then name the language families involved. The task before are more abstract, could be done with other languages as well.

**Comment by martino-vic** [comment]
I read through the talk quickly, seems very interesting and useful to me, especially regarding terminology - will have to catch up on that. I will read it more in detail in the evening.

And yes, the third part would be the qualitative one, where the expert decides which etymologies seem plausible and which don't. Ideally there would be some kind of baseline test as well, to estimate how much etymologies are randomly found in data sets where nothing should be found. That's what I had Wiktionary in mind for. But I think I would leave that for a separate paper and leave it out from my dissertation and from the workflow blog post, since it would be too much work

**Comment by martino-vic** [comment]
Uploaded a new version of the workflow, opened issue there https://github.com/martino-vic/martinovicgothun/issues/3#issue-1306875315

**Comment by martino-vic** [comment]
Provided a full workflow for the end-to-end process here: https://loanpy.readthedocs.io/en/latest/tutorial.html
