### ISSUE TITLE
Is IPAtok really needed?

### ISSUE THREAD

**Issue by LinguList** [LoanpyDataHub/loanpy#18]
You use IPA tok for a segmentation task, but ipatok is only needed if you have unsegmented text. We have with CLDF now the convention to only work whith pre-segmented data, and it is beneficial, as you can then concentrate on the coding aspect, not on data wrangling, in your library. So I suggest to drop the dependency and instead maybe go for an internal representation of the form similar to lingpy, e.g., using a `lingpy.basictype.strings` or `lingpy.basictypes.lists` (which is more complete):

Test this out:

```python
from lingpy import basictypes

tst = basictypes.lists("t h i s + i s + a + t e s t")
tst.n[1]
```

**Comment by martino-vic** [comment]
Do you know what the most elegant way would be to add a column like "Segments2" to forms.csv through the lexibank script?  I know it looks for an orhography.tsv in the etc folder and adds the column "Segments" automatically, but could it maybe be tweaked in a way that it's adding two of those columns somehow? Since loanpy is using two different types of segmentation, the other one being consonant/vowel clusters ("aebcdef" -> "ae bcd e f").

I wasn't aware that pre-segmented data became a convention. The main reason why I kept the tokeniser was because it was inherited from version 1.0, so it seemed easiest to just leave it there, since it didn't particularly disturb. Although I agree that it's quite a waste to take tokenised data as input, untokenise it and then retokenise it again

**Comment by LinguList** [comment]
Yes, it is easy to do so. But you need to explicitly change the type when loading CLDF data later. But even that can be changed (but I'd need to ask Robert there).

You need to adjust the `Lexeme` which is the default, and add a new "CV_Segments" to it:

```
@attr.s
class CustomLexeme(Lexeme):
    CV_Segments = attr.ib(default=None)
```

Then, while creating CLDF, you need to add this when adding the `args.writer.add_form_with_segments` or `args.writer.add_form`, or `args.writer.add_forms_from_value`, one of these three, do not remember what we originally use there.

**Comment by martino-vic** [comment]
Somehow I can't add this as a parameter in add_forms_from_value since the segmentation needs the forms, which is only available AFTER the forms table was created. I was trying to add the extra CV_Segments column separately at the bottom of the loop with `args.writer.objects["FormTable"].append({"CV_Segments": listofsegmentations})` but this threw a `KeyError: 'Parameter_ID'` - no idea why.

I also tried to add the extra segmentation column to orthography.tsv but obviously it didn't get copied to forms.csv

Only solution I could come up right now is to add the segmentation to the raw file but I guess that would be the wrong way to do it

**Comment by LinguList** [comment]
Can you make a separate issue in the underyling data repository and 
assign it to me?

**Comment by martino-vic** [comment]
Great, thank you, I opened this issue:

https://github.com/martino-vic/ronatasbertawot/issues/6#issue-1268650469

**Comment by martino-vic** [comment]
This is a good exercise actually to stick to the continuous integration. I tried out implementing these seemingly minor changes, locally (let's say in "sandbox mode") druing the last few days, but it's a bit like Jenga: pull out too many sticks too fast and the tower crashes. Well, I'll try to commit multiple small commits now and will see how far I can get

**Comment by martino-vic** [comment]
This took quite a while but finally the algorithm takes pre-tokenised data as input only. @LinguList maybe you can take a quick look and if it looks OK to you I'd close the issue. I managed to simplify a lot on the way so I think the changes were worth to implement.

**Comment by LinguList** [comment]
If we stick to the idea of the blog posts, we could start planning for August now (or do you plan for July?) and then I will check all relevant code blocks whenever we have one blogpost that introduces one step?

**Comment by martino-vic** [comment]
Sounds good!

**Comment by LinguList** [comment]
I am not a super-expert, but if you have this Jenga experience, I assume 
that it points to some lack of modularity. Ideally, code is made in such 
a way that you only need to modify this at one point. But of course, I 
know how difficult it is... If I find time, I can later double check if 
you do a proper PR where I can see changes.

**Comment by martino-vic** [comment]
removed IPA-tok as a dependency.
